services:
  pwa:
    container_name: pwa
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "3000:80"
    networks:
      pwa_net: