services:
  pwa:
    container_name: pwa
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    networks:
      - pwa_net

networks:
  pwa_net:
    driver: bridge
